const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const assert = require('node:assert/strict');

const {
  PROJECT_ROOT,
  buildOutputs,
  checkOutputs,
  createManifest,
  estimateTokens,
  renderMirror,
  renderPointer,
  renderScopedRule,
  resolveProjectPath,
  renderPipeline,
  validateConfig,
  validatePolicySet
} = require('../adapters/compiler');

test('builds concise native entries for every configured platform', () => {
  const build = buildOutputs('all');
  assert.deepEqual(
    build.outputs.map((output) => output.pipeline.platform),
    ['codex', 'cursor', 'claude', 'cline', 'copilot', 'gemini', 'antigravity', 'chatgpt']
  );
  for (const output of build.outputs) {
    assert.ok(output.lineCount <= build.config.maxEntryLines);
    assert.match(output.content, /AEOS-CONTEXT-001/);
    assert.match(output.content, /\.aeos\/knowledge\/standards\//);
  }
});

test('uses Cursor MDC front matter for Cursor output', () => {
  const { outputs } = buildOutputs('cursor');
  assert.match(outputs[0].content, /^---\ndescription:/);
  assert.match(outputs[0].content, /alwaysApply: true/);
});

test('renders repository mirrors with source-tree knowledge paths', () => {
  const { outputs, policySet } = buildOutputs('codex');
  const mirror = renderMirror(outputs[0], policySet);
  assert.match(mirror, /`\.context\/CURRENT\.md`/);
  assert.match(mirror, /`memory\/PROJECT_CONTEXT\.md`/);
  assert.match(mirror, /`standards\/`/);
  assert.doesNotMatch(mirror, /\.aeos\/knowledge/);
  assert.equal(mirror, renderPipeline(outputs[0].pipeline, policySet, 'repository'));
});

test('estimates tokens and enforces the token budget', () => {
  assert.equal(estimateTokens('abcd'), 1);
  assert.equal(estimateTokens('abcde'), 2);
  const build = buildOutputs('all');
  assert.ok(build.config.maxEntryTokens >= 100);
  for (const output of build.outputs) {
    assert.ok(output.tokenEstimate <= build.config.maxEntryTokens);
  }
  assert.throws(() => validateConfig({
    schemaVersion: 2,
    policySource: 'policies/core.json',
    knowledge: [],
    maxEntryLines: 120,
    maxEntryTokens: 50,
    pipelines: [{ platform: 'one', renderer: 'markdown', target: 'a', installTarget: 'a' }]
  }), /maxEntryTokens/);
});

test('supports platform aliases and rejects unknown platforms', () => {
  assert.equal(buildOutputs('claudecode').outputs[0].pipeline.platform, 'claude');
  assert.throws(() => buildOutputs('unknown'), /unknown platform/);
});

test('checked-in generated outputs match the policy source', () => {
  const build = buildOutputs('all');
  assert.deepEqual(checkOutputs(build), []);
  for (const output of build.outputs) {
    assert.equal(fs.readFileSync(path.join(PROJECT_ROOT, output.pipeline.target), 'utf8'), output.content);
  }
});

test('global manifest contains every configured platform', () => {
  const manifest = createManifest(buildOutputs('all'));
  assert.equal(manifest.files.length, 8);
  assert.equal(new Set(manifest.files.map((file) => file.platform)).size, 8);
});

test('renders short pointer entries that reference the canonical AGENTS.md', () => {
  const markdownPointer = renderPointer({ renderer: 'markdown' }, 'AGENTS.md');
  assert.match(markdownPointer, /Generated by AEOS/);
  assert.match(markdownPointer, /canonical AEOS entry is `AGENTS\.md`/);
  assert.doesNotMatch(markdownPointer, /AEOS-CONTEXT-001/);
  assert.ok(markdownPointer.trimEnd().split(/\r?\n/).length <= 15);

  const cursorPointer = renderPointer({ renderer: 'cursor' }, 'AGENTS.md');
  assert.match(cursorPointer, /^---\ndescription:/);
  assert.match(cursorPointer, /alwaysApply: true/);
});

test('config validation enforces canonical and readsAgentsMd invariants', () => {
  const base = {
    schemaVersion: 2,
    policySource: 'policies/core.json',
    knowledge: [],
    maxEntryLines: 120,
    pipelines: [
      { platform: 'one', renderer: 'markdown', target: 'a', installTarget: 'a', canonical: true },
      { platform: 'two', renderer: 'markdown', target: 'b', installTarget: 'b', canonical: true }
    ]
  };
  assert.throws(() => validateConfig(base), /at most one pipeline may be canonical/);
  assert.throws(() => validateConfig({
    ...base,
    pipelines: [{ platform: 'one', renderer: 'markdown', target: 'a', installTarget: 'a', readsAgentsMd: true }]
  }), /readsAgentsMd requires a canonical pipeline/);
  assert.throws(() => validateConfig({
    ...base,
    pipelines: [{ platform: 'one', renderer: 'markdown', target: 'a', installTarget: 'a', canonical: true, readsAgentsMd: true }]
  }), /cannot be both canonical and readsAgentsMd/);
});

test('config validation rejects duplicate aliases and invalid budgets', () => {
  const base = {
    schemaVersion: 2,
    policySource: 'policies/core.json',
    knowledge: [],
    maxEntryLines: 120,
    pipelines: [
      { platform: 'one', aliases: ['shared'], renderer: 'markdown', target: 'a', installTarget: 'a' },
      { platform: 'two', aliases: ['shared'], renderer: 'markdown', target: 'b', installTarget: 'b' }
    ]
  };
  assert.throws(() => validateConfig(base), /duplicate platform or alias/);
  assert.throws(() => validateConfig({ ...base, pipelines: base.pipelines.slice(0, 1), maxEntryLines: 2 }), /maxEntryLines/);
  assert.throws(() => validateConfig({
    ...base,
    pipelines: [{ platform: 'one', aliases: 'not-an-array', renderer: 'markdown', target: 'a', installTarget: 'a' }]
  }), /aliases must be an array/);
  assert.throws(() => validateConfig({
    ...base,
    pipelines: [{ platform: 'one', renderer: 'unknown', target: 'a', installTarget: 'a' }]
  }), /renderer is unsupported/);
  assert.throws(() => validateConfig({
    ...base,
    pipelines: [
      { platform: 'one', renderer: 'markdown', target: 'a', installTarget: 'RULES.md' },
      { platform: 'two', renderer: 'markdown', target: 'b', installTarget: 'rules.md' }
    ]
  }), /duplicate install target/);
  assert.throws(() => validateConfig({
    ...base,
    knowledge: ['standards', 'STANDARDS'],
    pipelines: base.pipelines.slice(0, 1)
  }), /knowledge directories must be unique/);
});

test('compiler paths cannot escape the AEOS repository', () => {
  assert.throws(() => resolveProjectPath('../outside', 'test path'), /escapes the AEOS repository/);
  const config = {
    schemaVersion: 2,
    policySource: 'policies/core.json',
    knowledge: [],
    maxEntryLines: 120,
    pipelines: [
      { platform: 'unsafe', renderer: 'markdown', target: '../outside', installTarget: 'safe.md' }
    ]
  };
  assert.throws(() => validateConfig(config), /escapes the AEOS repository/);
  assert.throws(
    () => validateConfig({ ...config, pipelines: [{ ...config.pipelines[0], target: 'dist/safe', installTarget: '../outside' }] }),
    /installTarget must stay inside/
  );
});

test('policy validation rejects duplicate IDs and unsupported renderers', () => {
  const valid = {
    id: 'AEOS-TEST-001',
    title: 'Test',
    level: 'required',
    scope: 'all',
    statement: 'Test statement.',
    rationale: 'Test rationale.',
    evidence: 'Test evidence.',
    source: 'constitution/constitution.md'
  };
  const metadata = { name: 'Test policies', description: 'Test policy set.' };
  assert.throws(() => validatePolicySet({
    ...metadata,
    schemaVersion: 1,
    precedence: ['host'],
    policies: [valid, { ...valid }]
  }), /duplicate policy id/);
  assert.throws(() => renderPipeline({ renderer: 'unknown' }, { policies: [], precedence: [] }), /unsupported renderer/);
  assert.throws(() => validatePolicySet({
    ...metadata,
    schemaVersion: 1,
    precedence: ['host'],
    policies: [{ ...valid, id: 'invalid' }]
  }), /must match AEOS/);
});

test('scoped-rule front matter safely quotes titles and globs', () => {
  const content = renderScopedRule({ renderer: 'cursor' }, {
    id: 'AEOS-TEST-001',
    title: 'Quoted: "title"',
    statement: 'Test.',
    evidence: 'Evidence.',
    level: 'required',
    appliesTo: ['src/**/*.js', 'package.json']
  });
  assert.match(content, /description: "AEOS-TEST-001/);
  assert.match(content, /globs: "src\/\*\*\/\*\.js,package\.json"/);
});
