const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(PROJECT_ROOT, 'adapters', 'config.json');
const GENERATED_MARKER = '<!-- Generated by AEOS. Do not edit directly. -->';

function resolveProjectPath(relativePath, fieldName) {
  if (typeof relativePath !== 'string' || !relativePath || path.isAbsolute(relativePath)) {
    throw new Error(`${fieldName} must be a non-empty relative path`);
  }
  const resolved = path.resolve(PROJECT_ROOT, relativePath);
  if (resolved !== PROJECT_ROOT && !resolved.startsWith(`${PROJECT_ROOT}${path.sep}`)) {
    throw new Error(`${fieldName} escapes the AEOS repository: ${relativePath}`);
  }
  return resolved;
}

function readJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (error) {
    throw new Error(`Cannot read JSON ${path.relative(PROJECT_ROOT, filePath)}: ${error.message}`);
  }
}

function validateConfig(config) {
  if (config.schemaVersion !== 2) throw new Error('adapters/config.json must use schemaVersion 2');
  if (typeof config.policySource !== 'string') throw new Error('policySource must be a string');
  resolveProjectPath(config.policySource, 'policySource');
  if (!Array.isArray(config.knowledge)) throw new Error('knowledge must be an array');
  for (const directory of config.knowledge) resolveProjectPath(directory, 'knowledge directory');
  if (!Number.isInteger(config.maxEntryLines) || config.maxEntryLines < 20) {
    throw new Error('maxEntryLines must be an integer of at least 20');
  }
  if (!Array.isArray(config.pipelines) || config.pipelines.length === 0) {
    throw new Error('pipelines must be a non-empty array');
  }

  const names = new Set();
  const targets = new Set();
  for (const pipeline of config.pipelines) {
    for (const field of ['platform', 'renderer', 'target', 'installTarget']) {
      if (typeof pipeline[field] !== 'string' || !pipeline[field]) {
        throw new Error(`pipeline.${field} must be a non-empty string`);
      }
    }
    for (const name of [pipeline.platform, ...(pipeline.aliases || [])]) {
      if (names.has(name)) throw new Error(`duplicate platform or alias: ${name}`);
      names.add(name);
    }
    if (targets.has(pipeline.target)) throw new Error(`duplicate build target: ${pipeline.target}`);
    resolveProjectPath(pipeline.target, `${pipeline.platform}.target`);
    if (path.isAbsolute(pipeline.installTarget) || pipeline.installTarget.split(/[\\/]/).includes('..')) {
      throw new Error(`${pipeline.platform}.installTarget must stay inside the target project`);
    }
    targets.add(pipeline.target);
    for (const mirror of pipeline.mirrors || []) {
      if (typeof mirror !== 'string' || !mirror) throw new Error('pipeline mirror must be a non-empty string');
      resolveProjectPath(mirror, `${pipeline.platform}.mirror`);
      if (targets.has(mirror)) throw new Error(`duplicate build target or mirror: ${mirror}`);
      targets.add(mirror);
    }
  }
}

function validatePolicySet(policySet) {
  if (policySet.schemaVersion !== 1) throw new Error('policies/core.json must use schemaVersion 1');
  if (!Array.isArray(policySet.precedence) || policySet.precedence.length === 0) {
    throw new Error('policy precedence must be a non-empty array');
  }
  if (!Array.isArray(policySet.policies) || policySet.policies.length === 0) {
    throw new Error('policies must be a non-empty array');
  }

  const ids = new Set();
  for (const policy of policySet.policies) {
    for (const field of ['id', 'title', 'level', 'scope', 'statement', 'rationale', 'evidence', 'source']) {
      if (typeof policy[field] !== 'string' || !policy[field].trim()) {
        throw new Error(`${policy.id || 'unknown policy'}.${field} must be a non-empty string`);
      }
    }
    if (!['required', 'recommended'].includes(policy.level)) {
      throw new Error(`${policy.id}.level must be required or recommended`);
    }
    if (ids.has(policy.id)) throw new Error(`duplicate policy id: ${policy.id}`);
    ids.add(policy.id);
    const sourcePath = resolveProjectPath(policy.source, `${policy.id}.source`);
    if (!fs.existsSync(sourcePath)) {
      throw new Error(`${policy.id} references missing source: ${policy.source}`);
    }
  }
}

function loadModel() {
  const config = readJson(CONFIG_PATH);
  validateConfig(config);
  const policyPath = path.join(PROJECT_ROOT, config.policySource);
  if (!fs.existsSync(policyPath)) throw new Error(`missing policy source: ${config.policySource}`);
  const policySet = readJson(policyPath);
  validatePolicySet(policySet);
  return { config, policySet };
}

function resolvePipelines(config, requestedPlatform) {
  if (requestedPlatform === 'all') return config.pipelines;
  const pipeline = config.pipelines.find((candidate) => (
    candidate.platform === requestedPlatform || (candidate.aliases || []).includes(requestedPlatform)
  ));
  if (!pipeline) {
    const supported = config.pipelines.map((candidate) => candidate.platform).join(', ');
    throw new Error(`unknown platform "${requestedPlatform}"; supported: ${supported}, all`);
  }
  return [pipeline];
}

function renderBody(policySet) {
  const required = policySet.policies.filter((policy) => policy.level === 'required');
  const recommended = policySet.policies.filter((policy) => policy.level === 'recommended');
  const lines = [
    '# AEOS Project Instructions',
    '',
    'AEOS is a repository guidance layer. It does not override host safety controls or explicit user instructions.',
    '',
    '## Precedence',
    '',
    ...policySet.precedence.map((item, index) => `${index + 1}. ${item}.`),
    '',
    '## Required',
    '',
    ...required.map((policy) => `- **${policy.id}**: ${policy.statement}`),
    '',
    '## Recommended',
    '',
    ...recommended.map((policy) => `- **${policy.id}**: ${policy.statement}`),
    '',
    '## Knowledge Map',
    '',
    '- Project facts and commands: `.aeos/PROJECT_CONTEXT.md`',
    '- Architecture and durable decisions: `.aeos/ARCHITECTURE.md` and `.aeos/DECISIONS.md`',
    '- Detailed standards: `.aeos/knowledge/standards/`',
    '- Task workflows: `.aeos/knowledge/workflows/`',
    '- Stack-specific guidance: `.aeos/knowledge/playbooks/`',
    '- Templates: `.aeos/knowledge/templates/`',
    '',
    'Load detailed documents only when they are relevant to the current task. Treat repository code and verified project facts as the source of truth.'
  ];
  return lines.join('\n');
}

function renderPipeline(pipeline, policySet) {
  const body = renderBody(policySet);
  if (pipeline.renderer === 'cursor') {
    return `---\ndescription: AEOS core engineering policy and knowledge map\nalwaysApply: true\n---\n\n${GENERATED_MARKER}\n\n${body}\n`;
  }
  if (pipeline.renderer === 'system') {
    return `${GENERATED_MARKER}\n\n${body}\n`;
  }
  if (['agents', 'markdown'].includes(pipeline.renderer)) {
    return `${GENERATED_MARKER}\n\n${body}\n`;
  }
  throw new Error(`unsupported renderer: ${pipeline.renderer}`);
}

function sha256(content) {
  return crypto.createHash('sha256').update(content).digest('hex');
}

function buildOutputs(requestedPlatform = 'all') {
  const { config, policySet } = loadModel();
  const outputs = resolvePipelines(config, requestedPlatform).map((pipeline) => {
    const content = renderPipeline(pipeline, policySet);
    const lineCount = content.trimEnd().split(/\r?\n/).length;
    if (lineCount > config.maxEntryLines) {
      throw new Error(`${pipeline.platform} entry has ${lineCount} lines; budget is ${config.maxEntryLines}`);
    }
    return { pipeline, content, hash: sha256(content), lineCount };
  });
  return { config, policySet, outputs };
}

function atomicWrite(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const temporaryPath = `${filePath}.tmp-${process.pid}`;
  fs.writeFileSync(temporaryPath, content, 'utf8');
  fs.renameSync(temporaryPath, filePath);
}

function renderMirrorContent(content) {
  return content
    .replaceAll('`.aeos/PROJECT_CONTEXT.md`', '`memory/PROJECT_CONTEXT.md`')
    .replaceAll('`.aeos/ARCHITECTURE.md`', '`memory/ARCHITECTURE.md`')
    .replaceAll('`.aeos/DECISIONS.md`', '`memory/DECISIONS.md`')
    .replaceAll('`.aeos/knowledge/', '`');
}

function writeOutputs(build) {
  for (const output of build.outputs) {
    atomicWrite(path.join(PROJECT_ROOT, output.pipeline.target), output.content);
    for (const mirror of output.pipeline.mirrors || []) {
      atomicWrite(path.join(PROJECT_ROOT, mirror), renderMirrorContent(output.content));
    }
  }
  writeManifest(build.outputs.length === build.config.pipelines.length ? build : buildOutputs('all'));
}

function createManifest(build) {
  return {
    schemaVersion: 1,
    policyHash: sha256(JSON.stringify(build.policySet)),
    files: build.outputs.map((output) => ({
      platform: output.pipeline.platform,
      path: output.pipeline.target.replace(/\\/g, '/'),
      sha256: output.hash,
      lines: output.lineCount
    }))
  };
}

function writeManifest(build) {
  const manifest = createManifest(build);
  atomicWrite(path.join(PROJECT_ROOT, 'dist', 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
}

function checkOutputs(build) {
  const drift = [];
  for (const output of build.outputs) {
    const targetPath = path.join(PROJECT_ROOT, output.pipeline.target);
    if (!fs.existsSync(targetPath) || fs.readFileSync(targetPath, 'utf8') !== output.content) {
      drift.push(output.pipeline.target);
    }
    for (const mirror of output.pipeline.mirrors || []) {
      const mirrorPath = path.join(PROJECT_ROOT, mirror);
      if (!fs.existsSync(mirrorPath) || fs.readFileSync(mirrorPath, 'utf8') !== renderMirrorContent(output.content)) {
        drift.push(mirror);
      }
    }
  }
  if (build.outputs.length === build.config.pipelines.length) {
    const manifestPath = path.join(PROJECT_ROOT, 'dist', 'manifest.json');
    const expectedManifest = `${JSON.stringify(createManifest(build), null, 2)}\n`;
    if (!fs.existsSync(manifestPath) || fs.readFileSync(manifestPath, 'utf8') !== expectedManifest) {
      drift.push('dist/manifest.json');
    }
  }
  return drift;
}

function parseArgs(argv) {
  let platform = 'all';
  let check = false;
  for (let index = 0; index < argv.length; index += 1) {
    if (['--platform', '-p'].includes(argv[index])) {
      if (!argv[index + 1]) throw new Error(`${argv[index]} requires a value`);
      platform = argv[index + 1].toLowerCase();
      index += 1;
    } else if (argv[index] === '--check') {
      check = true;
    } else {
      throw new Error(`unknown argument: ${argv[index]}`);
    }
  }
  return { platform, check };
}

function main() {
  try {
    const options = parseArgs(process.argv.slice(2));
    const build = buildOutputs(options.platform);
    if (options.check) {
      const drift = checkOutputs(build);
      if (drift.length > 0) throw new Error(`generated output is stale: ${drift.join(', ')}`);
      console.log(`AEOS check passed for ${build.outputs.length} platform(s).`);
      return;
    }
    writeOutputs(build);
    for (const output of build.outputs) {
      console.log(`Built ${output.pipeline.platform}: ${output.pipeline.target} (${output.lineCount} lines)`);
    }
  } catch (error) {
    console.error(`AEOS compiler error: ${error.message}`);
    process.exitCode = 1;
  }
}

if (require.main === module) main();

module.exports = {
  GENERATED_MARKER,
  PROJECT_ROOT,
  buildOutputs,
  checkOutputs,
  createManifest,
  loadModel,
  parseArgs,
  renderPipeline,
  renderMirrorContent,
  resolveProjectPath,
  sha256,
  validateConfig,
  validatePolicySet,
  writeManifest,
  writeOutputs
};
