const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(PROJECT_ROOT, 'adapters', 'config.json');
const GENERATED_MARKER = '<!-- Generated by AEOS. Do not edit directly. -->';
const SUPPORTED_RENDERERS = new Set(['agents', 'cursor', 'markdown', 'system']);

function portablePathKey(value) {
  return value.replace(/\\/g, '/').toLowerCase();
}

function validateTargetRelativePath(value, fieldName, { allowCurrentDirectory = false } = {}) {
  const normalized = value.replace(/\\/g, '/');
  if (path.isAbsolute(value) || /^[a-z]:/i.test(value) || normalized.split('/').includes('..')
    || (!allowCurrentDirectory && ['.', './'].includes(normalized))) {
    throw new Error(`${fieldName} must stay inside the target project`);
  }
  if (/[\r\n\0]/.test(value)) throw new Error(`${fieldName} cannot contain control characters`);
}

function resolveProjectPath(relativePath, fieldName) {
  if (typeof relativePath !== 'string' || !relativePath || path.isAbsolute(relativePath)) {
    throw new Error(`${fieldName} must be a non-empty relative path`);
  }
  const resolved = path.resolve(PROJECT_ROOT, relativePath);
  if (resolved !== PROJECT_ROOT && !resolved.startsWith(`${PROJECT_ROOT}${path.sep}`)) {
    throw new Error(`${fieldName} escapes the AEOS repository: ${relativePath}`);
  }
  return resolved;
}

function readJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (error) {
    throw new Error(`Cannot read JSON ${path.relative(PROJECT_ROOT, filePath)}: ${error.message}`);
  }
}

function validateConfig(config) {
  if (config.schemaVersion !== 2) throw new Error('adapters/config.json must use schemaVersion 2');
  if (typeof config.policySource !== 'string') throw new Error('policySource must be a string');
  resolveProjectPath(config.policySource, 'policySource');
  if (!Array.isArray(config.knowledge)) throw new Error('knowledge must be an array');
  if (new Set(config.knowledge.map(portablePathKey)).size !== config.knowledge.length) {
    throw new Error('knowledge directories must be unique');
  }
  for (const directory of config.knowledge) resolveProjectPath(directory, 'knowledge directory');
  if (!Number.isInteger(config.maxEntryLines) || config.maxEntryLines < 20) {
    throw new Error('maxEntryLines must be an integer of at least 20');
  }
  if (config.maxEntryTokens !== undefined && (!Number.isInteger(config.maxEntryTokens) || config.maxEntryTokens < 100)) {
    throw new Error('maxEntryTokens must be an integer of at least 100');
  }
  if (!Array.isArray(config.pipelines) || config.pipelines.length === 0) {
    throw new Error('pipelines must be a non-empty array');
  }

  const names = new Set();
  const targets = new Set();
  const installTargets = new Set();
  for (const pipeline of config.pipelines) {
    for (const field of ['platform', 'renderer', 'target', 'installTarget']) {
      if (typeof pipeline[field] !== 'string' || !pipeline[field]) {
        throw new Error(`pipeline.${field} must be a non-empty string`);
      }
    }
    for (const field of ['canonical', 'readsAgentsMd', 'scopedRules', 'commands']) {
      if (pipeline[field] !== undefined && typeof pipeline[field] !== 'boolean') {
        throw new Error(`${pipeline.platform}.${field} must be a boolean`);
      }
    }
    if (!SUPPORTED_RENDERERS.has(pipeline.renderer)) {
      throw new Error(`${pipeline.platform}.renderer is unsupported: ${pipeline.renderer}`);
    }
    if (pipeline.aliases !== undefined && (!Array.isArray(pipeline.aliases)
      || pipeline.aliases.some((alias) => typeof alias !== 'string' || !alias))) {
      throw new Error(`${pipeline.platform}.aliases must be an array of non-empty strings`);
    }
    if (pipeline.mirrors !== undefined && (!Array.isArray(pipeline.mirrors)
      || pipeline.mirrors.some((mirror) => typeof mirror !== 'string' || !mirror))) {
      throw new Error(`${pipeline.platform}.mirrors must be an array of non-empty strings`);
    }
    if (pipeline.scopedRules && !['cursor', 'markdown'].includes(pipeline.renderer)) {
      throw new Error(`${pipeline.platform}.scopedRules requires a cursor or markdown renderer`);
    }
    if (pipeline.commandsTarget !== undefined) {
      if (typeof pipeline.commandsTarget !== 'string' || !pipeline.commandsTarget) {
        throw new Error(`${pipeline.platform}.commandsTarget must be a non-empty string`);
      }
      validateTargetRelativePath(pipeline.commandsTarget, `${pipeline.platform}.commandsTarget`, { allowCurrentDirectory: true });
      if (!pipeline.commands) throw new Error(`${pipeline.platform}.commandsTarget requires commands: true`);
    }
    if (pipeline.canonical && pipeline.readsAgentsMd) {
      throw new Error(`${pipeline.platform} cannot be both canonical and readsAgentsMd`);
    }
    for (const name of [pipeline.platform, ...(pipeline.aliases || [])]) {
      const normalizedName = name.toLowerCase();
      if (names.has(normalizedName)) throw new Error(`duplicate platform or alias: ${name}`);
      names.add(normalizedName);
    }
    const targetKey = portablePathKey(pipeline.target);
    if (targets.has(targetKey)) throw new Error(`duplicate build target: ${pipeline.target}`);
    resolveProjectPath(pipeline.target, `${pipeline.platform}.target`);
    validateTargetRelativePath(pipeline.installTarget, `${pipeline.platform}.installTarget`);
    const installTargetKey = portablePathKey(pipeline.installTarget);
    if (installTargets.has(installTargetKey)) throw new Error(`duplicate install target: ${pipeline.installTarget}`);
    installTargets.add(installTargetKey);
    targets.add(targetKey);
    for (const mirror of pipeline.mirrors || []) {
      resolveProjectPath(mirror, `${pipeline.platform}.mirror`);
      const mirrorKey = portablePathKey(mirror);
      if (targets.has(mirrorKey)) throw new Error(`duplicate build target or mirror: ${mirror}`);
      targets.add(mirrorKey);
    }
  }

  const canonicalPipelines = config.pipelines.filter((pipeline) => pipeline.canonical);
  if (canonicalPipelines.length > 1) {
    throw new Error(`at most one pipeline may be canonical; found: ${canonicalPipelines.map((p) => p.platform).join(', ')}`);
  }
  if (canonicalPipelines.length === 0 && config.pipelines.some((pipeline) => pipeline.readsAgentsMd)) {
    throw new Error('readsAgentsMd requires a canonical pipeline');
  }
}

function validatePolicySet(policySet) {
  if (policySet.schemaVersion !== 1) throw new Error('policies/core.json must use schemaVersion 1');
  for (const field of ['name', 'description']) {
    if (typeof policySet[field] !== 'string' || !policySet[field].trim()) {
      throw new Error(`policy ${field} must be a non-empty string`);
    }
  }
  if (!Array.isArray(policySet.precedence) || policySet.precedence.length === 0) {
    throw new Error('policy precedence must be a non-empty array');
  }
  if (policySet.precedence.some((item) => typeof item !== 'string' || !item.trim())) {
    throw new Error('policy precedence must contain non-empty strings');
  }
  if (!Array.isArray(policySet.policies) || policySet.policies.length === 0) {
    throw new Error('policies must be a non-empty array');
  }

  const ids = new Set();
  for (const policy of policySet.policies) {
    for (const field of ['id', 'title', 'level', 'scope', 'statement', 'rationale', 'evidence', 'source']) {
      if (typeof policy[field] !== 'string' || !policy[field].trim()) {
        throw new Error(`${policy.id || 'unknown policy'}.${field} must be a non-empty string`);
      }
    }
    if (!['required', 'recommended'].includes(policy.level)) {
      throw new Error(`${policy.id}.level must be required or recommended`);
    }
    if (!/^AEOS-[A-Z]+-[0-9]{3}$/.test(policy.id)) {
      throw new Error(`${policy.id}.id must match AEOS-<AREA>-<NNN>`);
    }
    if (ids.has(policy.id)) throw new Error(`duplicate policy id: ${policy.id}`);
    ids.add(policy.id);
    if (policy.appliesTo !== undefined) {
      if (!Array.isArray(policy.appliesTo) || policy.appliesTo.length === 0
        || policy.appliesTo.some((glob) => typeof glob !== 'string' || !glob.trim() || /[\r\n\0]/.test(glob))) {
        throw new Error(`${policy.id}.appliesTo must be a non-empty array of glob strings`);
      }
    }
    const sourcePath = resolveProjectPath(policy.source, `${policy.id}.source`);
    if (!fs.existsSync(sourcePath)) {
      throw new Error(`${policy.id} references missing source: ${policy.source}`);
    }
  }
}

function loadModel() {
  const config = readJson(CONFIG_PATH);
  validateConfig(config);
  const policyPath = path.join(PROJECT_ROOT, config.policySource);
  if (!fs.existsSync(policyPath)) throw new Error(`missing policy source: ${config.policySource}`);
  const policySet = readJson(policyPath);
  validatePolicySet(policySet);
  return { config, policySet };
}

function resolvePipelines(config, requestedPlatform) {
  if (requestedPlatform === 'all') return config.pipelines;
  const pipeline = config.pipelines.find((candidate) => (
    candidate.platform === requestedPlatform || (candidate.aliases || []).includes(requestedPlatform)
  ));
  if (!pipeline) {
    const supported = config.pipelines.map((candidate) => candidate.platform).join(', ');
    throw new Error(`unknown platform "${requestedPlatform}"; supported: ${supported}, all`);
  }
  return [pipeline];
}

const PATH_CONTEXTS = {
  install: {
    recovery: null,
    facts: '.aeos/PROJECT_CONTEXT.md',
    architecture: '.aeos/ARCHITECTURE.md',
    decisions: '.aeos/DECISIONS.md',
    knowledgePrefix: '.aeos/knowledge/'
  },
  repository: {
    recovery: '.context/CURRENT.md',
    facts: 'memory/PROJECT_CONTEXT.md',
    architecture: 'memory/ARCHITECTURE.md',
    decisions: 'memory/DECISIONS.md',
    knowledgePrefix: ''
  }
};

function renderBody(policySet, context = 'install') {
  const paths = PATH_CONTEXTS[context];
  if (!paths) throw new Error(`unknown path context: ${context}`);
  const required = policySet.policies.filter((policy) => policy.level === 'required');
  const recommended = policySet.policies.filter((policy) => policy.level === 'recommended');
  const lines = [
    '# AEOS Project Instructions',
    '',
    'AEOS is a repository guidance layer. It does not override host safety controls or explicit user instructions.',
    '',
    '## Precedence',
    '',
    ...policySet.precedence.map((item, index) => `${index + 1}. ${item}.`),
    '',
    '## Required',
    '',
    ...required.map((policy) => `- **${policy.id}**: ${policy.statement}`),
    '',
    '## Recommended',
    '',
    ...recommended.map((policy) => `- **${policy.id}**: ${policy.statement}`),
    '',
    '## Knowledge Map',
    '',
    ...(paths.recovery ? [`- Rapid recovery context: \`${paths.recovery}\``] : []),
    `- Project facts and commands: \`${paths.facts}\``,
    `- Architecture and durable decisions: \`${paths.architecture}\` and \`${paths.decisions}\``,
    `- Detailed standards: \`${paths.knowledgePrefix}standards/\``,
    `- Task workflows: \`${paths.knowledgePrefix}workflows/\``,
    `- Stack-specific guidance: \`${paths.knowledgePrefix}playbooks/\``,
    `- Templates: \`${paths.knowledgePrefix}templates/\``,
    '',
    'Load detailed documents only when they are relevant to the current task. Treat repository code and verified project facts as the source of truth.'
  ];
  return lines.join('\n');
}

function renderPipeline(pipeline, policySet, context = 'install') {
  const body = renderBody(policySet, context);
  if (pipeline.renderer === 'cursor') {
    return `---\ndescription: AEOS core engineering policy and knowledge map\nalwaysApply: true\n---\n\n${GENERATED_MARKER}\n\n${body}\n`;
  }
  if (['agents', 'markdown', 'system'].includes(pipeline.renderer)) {
    return `${GENERATED_MARKER}\n\n${body}\n`;
  }
  throw new Error(`unsupported renderer: ${pipeline.renderer}`);
}

function renderPointer(pipeline, canonicalInstallTarget) {
  const body = [
    '# AEOS Project Instructions',
    '',
    `This project uses AEOS. The canonical AEOS entry is \`${canonicalInstallTarget}\` at the repository root.`,
    '',
    `Read \`${canonicalInstallTarget}\` for the required policies, precedence, and knowledge map.`,
    `If your client already loads \`${canonicalInstallTarget}\` natively, ignore this file to avoid duplicate context.`
  ].join('\n');
  if (pipeline.renderer === 'cursor') {
    return `---\ndescription: AEOS pointer to the canonical ${canonicalInstallTarget} entry\nalwaysApply: true\n---\n\n${GENERATED_MARKER}\n\n${body}\n`;
  }
  return `${GENERATED_MARKER}\n\n${body}\n`;
}

function renderScopedRule(pipeline, policy) {
  const globs = policy.appliesTo.join(',');
  const body = [
    `# ${policy.id}: ${policy.title}`,
    '',
    policy.statement,
    '',
    `Evidence expected: ${policy.evidence}`,
    '',
    `This is a scoped reminder of an AEOS ${policy.level} policy; the full policy set is in the AEOS entry file.`
  ].join('\n');
  if (pipeline.renderer === 'cursor') {
    return `---\ndescription: ${JSON.stringify(`${policy.id} — ${policy.title}`)}\nglobs: ${JSON.stringify(globs)}\nalwaysApply: false\n---\n\n${GENERATED_MARKER}\n\n${body}\n`;
  }
  if (pipeline.renderer === 'markdown') {
    return `---\napplyTo: ${JSON.stringify(globs)}\n---\n\n${GENERATED_MARKER}\n\n${body}\n`;
  }
  throw new Error(`scoped rules are not supported for renderer: ${pipeline.renderer}`);
}

function scopedRuleTarget(pipeline, policy) {
  const slug = policy.id.toLowerCase();
  if (pipeline.renderer === 'cursor') return `.cursor/rules/${slug}.mdc`;
  if (pipeline.renderer === 'markdown') return `.github/instructions/${slug}.instructions.md`;
  throw new Error(`scoped rules are not supported for renderer: ${pipeline.renderer}`);
}

function renderCommand(workflowName, workflowContent) {
  const title = workflowName.replace(/[-_]+/g, ' ');
  return [
    '---',
    `description: Run the AEOS ${title} workflow for the current task`,
    'argument-hint: [task or context]',
    '---',
    '',
    GENERATED_MARKER,
    '',
    `Follow this AEOS workflow for the task described in $ARGUMENTS (or the current conversation if empty).`,
    'Apply it proportionally to task risk; skip steps that clearly do not apply and say so.',
    '',
    workflowContent.trim(),
    ''
  ].join('\n');
}

function sha256(content) {
  return crypto.createHash('sha256').update(content).digest('hex');
}

function estimateTokens(content) {
  return Math.ceil(content.length / 4);
}

function buildOutputs(requestedPlatform = 'all') {
  const { config, policySet } = loadModel();
  const outputs = resolvePipelines(config, requestedPlatform).map((pipeline) => {
    const content = renderPipeline(pipeline, policySet);
    const lineCount = content.trimEnd().split(/\r?\n/).length;
    if (lineCount > config.maxEntryLines) {
      throw new Error(`${pipeline.platform} entry has ${lineCount} lines; budget is ${config.maxEntryLines}`);
    }
    const tokenEstimate = estimateTokens(content);
    if (config.maxEntryTokens && tokenEstimate > config.maxEntryTokens) {
      throw new Error(`${pipeline.platform} entry is ~${tokenEstimate} tokens; budget is ${config.maxEntryTokens}`);
    }
    return { pipeline, content, hash: sha256(content), lineCount, tokenEstimate };
  });
  return { config, policySet, outputs };
}

function atomicWrite(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const temporaryPath = `${filePath}.tmp-${process.pid}-${crypto.randomUUID()}`;
  try {
    fs.writeFileSync(temporaryPath, content, { encoding: 'utf8', flag: 'wx' });
    fs.renameSync(temporaryPath, filePath);
  } finally {
    if (fs.existsSync(temporaryPath)) fs.rmSync(temporaryPath, { force: true });
  }
}

function renderMirror(output, policySet) {
  return renderPipeline(output.pipeline, policySet, 'repository');
}

function writeOutputs(build) {
  for (const output of build.outputs) {
    atomicWrite(path.join(PROJECT_ROOT, output.pipeline.target), output.content);
    for (const mirror of output.pipeline.mirrors || []) {
      atomicWrite(path.join(PROJECT_ROOT, mirror), renderMirror(output, build.policySet));
    }
  }
  writeManifest(build.outputs.length === build.config.pipelines.length ? build : buildOutputs('all'));
}

function createManifest(build) {
  return {
    schemaVersion: 1,
    policyHash: sha256(JSON.stringify(build.policySet)),
    files: build.outputs.map((output) => ({
      platform: output.pipeline.platform,
      path: output.pipeline.target.replace(/\\/g, '/'),
      sha256: output.hash,
      lines: output.lineCount,
      tokens: output.tokenEstimate
    }))
  };
}

function writeManifest(build) {
  const manifest = createManifest(build);
  atomicWrite(path.join(PROJECT_ROOT, 'dist', 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
}

function checkOutputs(build) {
  const drift = [];
  for (const output of build.outputs) {
    const targetPath = path.join(PROJECT_ROOT, output.pipeline.target);
    if (!fs.existsSync(targetPath) || fs.readFileSync(targetPath, 'utf8') !== output.content) {
      drift.push(output.pipeline.target);
    }
    for (const mirror of output.pipeline.mirrors || []) {
      const mirrorPath = path.join(PROJECT_ROOT, mirror);
      if (!fs.existsSync(mirrorPath) || fs.readFileSync(mirrorPath, 'utf8') !== renderMirror(output, build.policySet)) {
        drift.push(mirror);
      }
    }
  }
  if (build.outputs.length === build.config.pipelines.length) {
    const manifestPath = path.join(PROJECT_ROOT, 'dist', 'manifest.json');
    const expectedManifest = `${JSON.stringify(createManifest(build), null, 2)}\n`;
    if (!fs.existsSync(manifestPath) || fs.readFileSync(manifestPath, 'utf8') !== expectedManifest) {
      drift.push('dist/manifest.json');
    }
  }
  return drift;
}

function parseArgs(argv) {
  let platform = 'all';
  let check = false;
  for (let index = 0; index < argv.length; index += 1) {
    if (['--platform', '-p'].includes(argv[index])) {
      if (!argv[index + 1]) throw new Error(`${argv[index]} requires a value`);
      platform = argv[index + 1].toLowerCase();
      index += 1;
    } else if (argv[index] === '--check') {
      check = true;
    } else {
      throw new Error(`unknown argument: ${argv[index]}`);
    }
  }
  return { platform, check };
}

function main() {
  try {
    const options = parseArgs(process.argv.slice(2));
    const build = buildOutputs(options.platform);
    if (options.check) {
      const drift = checkOutputs(build);
      if (drift.length > 0) throw new Error(`generated output is stale: ${drift.join(', ')}`);
      console.log(`AEOS check passed for ${build.outputs.length} platform(s).`);
      return;
    }
    writeOutputs(build);
    for (const output of build.outputs) {
      console.log(`Built ${output.pipeline.platform}: ${output.pipeline.target} (${output.lineCount} lines)`);
    }
  } catch (error) {
    console.error(`AEOS compiler error: ${error.message}`);
    process.exitCode = 1;
  }
}

if (require.main === module) main();

module.exports = {
  GENERATED_MARKER,
  PATH_CONTEXTS,
  PROJECT_ROOT,
  buildOutputs,
  checkOutputs,
  createManifest,
  estimateTokens,
  loadModel,
  parseArgs,
  renderCommand,
  renderPipeline,
  renderMirror,
  renderPointer,
  renderScopedRule,
  resolveProjectPath,
  scopedRuleTarget,
  sha256,
  validateConfig,
  validatePolicySet,
  writeManifest,
  writeOutputs
};
